spring:
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect # hibernate : ???? sql ? ??
      ddl-auto: update   # ddl ?? ???? : ????? ???? ??? ???? ??? ???
    properties:
      hibernate:
        format_sql: true # sql ? ?? ?? ??
    show-sql: true       # sql ?? ????? ??

# DB ??? ?? ?? datasource
spring.datasource:
  hikari.maximum-pool-size: 4  # DB ??? ?
  url:
  username:
  password:
  platform:
  driver-class-name:
